"""Orchestrates the immersive scene generation pipeline end to end."""

from __future__ import annotations

import re
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from . import audio, claude_client, elevenlabs_client, prompts, voices


def _slugify(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")
    return slug or "artwork"


def generate_immersive_scene(
    artwork_name: str,
    artwork_info: str,
    *,
    artist_name: str = "",
    language: str = "français",
    age: str = "adulte",
    narration_text: str | None = None,
    output_dir: str | Path = "outputs",
) -> Path:
    """
    Generate a full immersive audio scene for an artwork: tour-guide narration,
    an ambient soundscape, and a short multi-voice theatrical dialogue, mixed
    into a single final .wav file.

    `narration_text`, if provided (e.g. already generated by a host app), is used
    as-is instead of asking Claude to write a new tour-guide description.

    Returns the path to the generated file.
    """
    out_dir = Path(output_dir) / _slugify(artwork_name)
    out_dir.mkdir(parents=True, exist_ok=True)

    claude = claude_client.get_client()
    description = narration_text or claude_client.ask(
        claude, prompts.get_artwork_description_prompt(artwork_name, artist_name, artwork_info)
    )

    content = claude_client.generate_immersive_content(
        claude,
        prompts.get_soundscape_and_dialogue_prompt(
            artwork_name, artist_name, artwork_info, description, language=language, age=age
        ),
    )

    eleven = elevenlabs_client.get_client()
    dialogue_lines = [
        (line.text, voices.character_voice_id(line.voice.gender, i))
        for i, line in enumerate(content.dialogue)
    ]

    # Narration, soundscape, and dialogue are independent ElevenLabs calls —
    # run them concurrently instead of one after another.
    with ThreadPoolExecutor(max_workers=3) as pool:
        narration_future = pool.submit(
            elevenlabs_client.text_to_speech, eleven, description, voices.NARRATOR_VOICE_ID
        )
        soundscape_future = pool.submit(
            elevenlabs_client.text_to_sound_effects, eleven, content.soundscape_prompt
        )
        dialogue_future = pool.submit(elevenlabs_client.text_to_dialogue, eleven, dialogue_lines)

        narration_audio = audio.bytes_to_segment(narration_future.result())
        soundscape_audio = audio.bytes_to_segment(soundscape_future.result())
        dialogue_audio = audio.bytes_to_segment(dialogue_future.result())

    spoken_track = audio.concat_with_silence([narration_audio, dialogue_audio], gap_ms=1500)
    looped_background = audio.loop_to_length(soundscape_audio, len(spoken_track))
    final = audio.mix(looped_background, spoken_track, bg_gain_db=-8, fg_gain_db=0)

    output_path = out_dir / "final_scene.wav"
    final.export(output_path, format="wav")
    return output_path
